#!/bin/sh -e

# Copyright 2019 Oliver Cope
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


. gup/GUPVARS

SRC="$SRC_STEM.png"
gup -u $SRC

# Quantize color palette
pngquant -v -f --quality 0-90 -o $1.tmp $SRC
ls -l $1.tmp

# -nx disables optimizations already done in previous step
optipng -quiet -o5 -nx $1.tmp
ls -l $1.tmp

# Recode and optimize deflate stream
advdef -z -4 $1.tmp
mv $1.tmp $1
ls -l $1
