#!/bin/sh -e

PROJECT_ROOT=$(hg root 2>/dev/null || git rev-parse --show-toplevel)
. $PROJECT_ROOT/gup/GUPVARS

SRC="${SRC_STEM}.scss"
gup -u $SRC $(findscssimports $SRC)
$SASS $SRC | $AUTOPREFIXER | $CLEANCSS > $1
