#!/bin/sh

PYTHON="python3.8"
gup --leave
PROJECT_ROOT=$(hg root 2>/dev/null || git rev-parse --show-toplevel)

case $2 in
    */python)
        cd "$PROJECT_ROOT" && "$PYTHON" -mvenv venv
        exit $?
        ;;
esac
gup -u requirements.txt venv/bin/python

for dep in requirements-dev.txt setup.py setup.cfg; do
    if [ -f "$dep" ]; then
        gup -u $dep
    fi
done

if [ -f requirements-dev.txt ]; then
    ./venv/bin/pip install -r requirements-dev.txt
else
    ./venv/bin/pip install -r requirements.txt
fi
