#!/bin/sh

# Copyright 2019 Oliver Cope
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PYTHON="python3.8"
gup --leave

case $2 in
    */python)
        cd "$(hg root)" && "$PYTHON" -mvenv venv
        exit $?
        ;;
esac
gup -u requirements.txt venv/bin/python

for dep in requirements-dev.txt setup.py setup.cfg; do
    if [ -f "$dep" ]; then
        gup -u $dep
    fi
done

if [ -f requirements-dev.txt ]; then
    ./venv/bin/pip install -r requirements-dev.txt
else
    ./venv/bin/pip install -r requirements.txt
fi
